name: Deploy Documentation

on:
  # Trigger on push to main branch
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'cosi_consumer_framework/**'
      - '.github/workflows/docs.yml'
  
  # Trigger on pull request merge to main
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'cosi_consumer_framework/**'
      - '.github/workflows/docs.yml'
  
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    # Only run if push to main OR if PR was merged (not just closed)
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate git info
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: |
          uv sync --group dev
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Build documentation
        run: |
          uv run mkdocs build --strict
        env:
          # Set the site URL to the GitHub Pages URL
          MKDOCS_CONFIG_SITE_URL: ${{ steps.pages.outputs.base_url }}/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4